### ISSUE TITLE
missing libjpeg62

### ISSUE THREAD

**Issue by Rad-dude** [treanus/KUL_Linux_Installation#1]
Hello,

This package (libjpeg62) was missing in my linux mint 20 and it prevented freeview (from FS v.6.0) from working correctly.
It seems to be a known issue but finding the correct solution was not easy.

This didn't work:
sudo apt-get install -y libjpeg-dev

But this did:
https://docs.quantumatk.com/faq/faq_installation_noopen62.html
just a simple install of the library: sudo apt-get install libjpeg62

Might be a good idea to add it. Otherwise, the script worked perfectly! so thanks a lot :)

**Comment by treanus** [comment]
Resolved
